import type { Metadata } from "next";
import { Pixelify_Sans, Delius_Swash_Caps } from 'next/font/google';
import "./globals.css";

const pixelifySans = Pixelify_Sans({ subsets: ['latin'], variable: '--font-pixelify-sans' });
const deliusSwashCaps = Delius_Swash_Caps({ subsets: ['latin'], weight: '400', variable: '--font-delius-swash-caps' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pixelifySans.variable} ${deliusSwashCaps.variable}`}>
        {children}
      </body>
    </html>
  );
}
